import type { User, Video, Comment } from './types';

export const MOCK_USERS: User[] = [
  { id: 'user1', username: '@CreativeCoder', avatarUrl: 'https://picsum.photos/id/1005/100/100' },
  { id: 'user2', username: '@AI_Explorer', avatarUrl: 'https://picsum.photos/id/1011/100/100' },
  { id: 'user3', username: '@PixelPioneer', avatarUrl: 'https://picsum.photos/id/1025/100/100' },
  { id: 'user4', username: '@SynthwaveSurfer', avatarUrl: 'https://picsum.photos/id/103/100/100' },
];

const MOCK_COMMENTS_VID1: Comment[] = [
    { id: 'c1', user: MOCK_USERS[1], text: 'This looks amazing! What software did you use?' },
    { id: 'c2', user: MOCK_USERS[2], text: 'So smooth! Love the colors.' },
];

const MOCK_COMMENTS_VID2: Comment[] = [
    { id: 'c3', user: MOCK_USERS[0], text: 'Wow, I need to go there! Breathtaking view.' },
    { id: 'c4', user: MOCK_USERS[3], text: 'Incredible shot! Looks like a postcard.' },
    { id: 'c5', user: MOCK_USERS[1], text: 'Thanks everyone! It was an unforgettable trip.' },
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'vid1',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid1/400/225',
    title: 'Fun Times with Animation',
    uploader: MOCK_USERS[0],
    description: 'Having a blast with this new animation software! #animation #creative',
    likes: 1204,
    comments: MOCK_COMMENTS_VID1,
    isLiked: false,
    duration: 15,
    views: 15300,
  },
  {
    id: 'vid2',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid2/400/225',
    title: 'Patagonia Landscapes',
    uploader: MOCK_USERS[1],
    description: 'Exploring the breathtaking landscapes of Patagonia. Nature is amazing! 🏔️',
    likes: 3456,
    comments: MOCK_COMMENTS_VID2,
    isLiked: true,
    duration: 15,
    views: 45800,
  },
    {
    id: 'vid5',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid5/400/225',
    title: 'Big Buck Bunny',
    uploader: MOCK_USERS[2],
    description: 'A classic short film by the Blender Institute. A story of a gentle giant rabbit.',
    likes: 15000,
    comments: [],
    isLiked: false,
    duration: 596,
    views: 2300000,
  },
  {
    id: 'vid3',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid3/400/225',
    title: 'First AI Generative Art',
    uploader: MOCK_USERS[2],
    description: 'My first attempt at generative art with AI. What do you think?',
    likes: 879,
    comments: [],
    isLiked: false,
    duration: 15,
    views: 9200,
  },
  {
    id: 'vid6',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid6/400/225',
    title: 'Elephants Dream',
    uploader: MOCK_USERS[0],
    description: 'Another beautiful and surreal open-source movie made with Blender.',
    likes: 12000,
    comments: [],
    isLiked: false,
    duration: 653,
    views: 1800000,
  },
  {
    id: 'vid4',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid4/400/225',
    title: 'Late Night Synthwave Drive',
    uploader: MOCK_USERS[3],
    description: 'Nothing beats a good synthwave track on a late-night drive. #synthwave #vibes',
    likes: 5612,
    comments: [],
    isLiked: false,
    duration: 15,
    views: 88000,
  },
    {
    id: 'vid7',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid7/400/225',
    title: 'Sintel - Blender Open Movie',
    uploader: MOCK_USERS[1],
    description: 'An epic fantasy adventure. A girl searches for her pet dragon.',
    likes: 25000,
    comments: [],
    isLiked: true,
    duration: 888,
    views: 5400000,
  },
];